"""Install entry rejection reason codes."""

INSTALL_REJECT_MULTI_GPU_BLOCKED = "multi_gpu_blocked"
INSTALL_REJECT_INSTALL_IN_PROGRESS = "install_in_progress"
INSTALL_REJECT_PREDOWNLOAD_IN_PROGRESS = "predownload_in_progress"
INSTALL_REJECT_NO_GAME_SELECTED = "no_game_selected"
INSTALL_REJECT_OPTISCALER_ARCHIVE_DOWNLOADING = "optiscaler_archive_downloading"
INSTALL_REJECT_INSTALL_PRECHECK_RUNNING = "install_precheck_running"
INSTALL_REJECT_PRECHECK_INCOMPLETE = "precheck_incomplete"
INSTALL_REJECT_OPTISCALER_ARCHIVE_NOT_READY = "optiscaler_archive_not_ready"
INSTALL_REJECT_INVALID_GAME_SELECTION = "invalid_game_selection"
INSTALL_REJECT_FSR4_ARCHIVE_DOWNLOADING = "fsr4_archive_downloading"
INSTALL_REJECT_FSR4_NOT_READY = "fsr4_not_ready"
INSTALL_REJECT_CONFIRM_POPUP_REQUIRED = "confirm_popup_required"

__all__ = [
    "INSTALL_REJECT_CONFIRM_POPUP_REQUIRED",
    "INSTALL_REJECT_FSR4_ARCHIVE_DOWNLOADING",
    "INSTALL_REJECT_FSR4_NOT_READY",
    "INSTALL_REJECT_INSTALL_IN_PROGRESS",
    "INSTALL_REJECT_INSTALL_PRECHECK_RUNNING",
    "INSTALL_REJECT_INVALID_GAME_SELECTION",
    "INSTALL_REJECT_MULTI_GPU_BLOCKED",
    "INSTALL_REJECT_NO_GAME_SELECTED",
    "INSTALL_REJECT_OPTISCALER_ARCHIVE_DOWNLOADING",
    "INSTALL_REJECT_OPTISCALER_ARCHIVE_NOT_READY",
    "INSTALL_REJECT_PRECHECK_INCOMPLETE",
    "INSTALL_REJECT_PREDOWNLOAD_IN_PROGRESS",
]
