"""Install button disabled reason codes."""

INSTALL_BUTTON_REASON_MULTI_GPU_BLOCKED = "multi_gpu_blocked"
INSTALL_BUTTON_REASON_GPU_SELECTION_PENDING = "gpu_selection_pending"
INSTALL_BUTTON_REASON_SHEET_LOADING = "sheet_loading"
INSTALL_BUTTON_REASON_SHEET_NOT_READY = "sheet_not_ready"
INSTALL_BUTTON_REASON_INSTALL_IN_PROGRESS = "install_in_progress"
INSTALL_BUTTON_REASON_APP_UPDATE_IN_PROGRESS = "app_update_in_progress"
INSTALL_BUTTON_REASON_NO_GAME_SELECTED = "no_game_selected"
INSTALL_BUTTON_REASON_INSTALL_PRECHECK_RUNNING = "install_precheck_running"
INSTALL_BUTTON_REASON_PRECHECK_INCOMPLETE = "precheck_incomplete"
INSTALL_BUTTON_REASON_OPTISCALER_ARCHIVE_DOWNLOADING = "optiscaler_archive_downloading"
INSTALL_BUTTON_REASON_OPTISCALER_ARCHIVE_NOT_READY = "optiscaler_archive_not_ready"
INSTALL_BUTTON_REASON_FSR4_NOT_READY = "fsr4_not_ready"
INSTALL_BUTTON_REASON_UNSUPPORTED_GPU = "unsupported_gpu"
INSTALL_BUTTON_REASON_CONFIRM_POPUP_REQUIRED = "confirm_popup_required"

__all__ = [
    "INSTALL_BUTTON_REASON_APP_UPDATE_IN_PROGRESS",
    "INSTALL_BUTTON_REASON_CONFIRM_POPUP_REQUIRED",
    "INSTALL_BUTTON_REASON_FSR4_NOT_READY",
    "INSTALL_BUTTON_REASON_GPU_SELECTION_PENDING",
    "INSTALL_BUTTON_REASON_INSTALL_IN_PROGRESS",
    "INSTALL_BUTTON_REASON_INSTALL_PRECHECK_RUNNING",
    "INSTALL_BUTTON_REASON_MULTI_GPU_BLOCKED",
    "INSTALL_BUTTON_REASON_NO_GAME_SELECTED",
    "INSTALL_BUTTON_REASON_OPTISCALER_ARCHIVE_DOWNLOADING",
    "INSTALL_BUTTON_REASON_OPTISCALER_ARCHIVE_NOT_READY",
    "INSTALL_BUTTON_REASON_PRECHECK_INCOMPLETE",
    "INSTALL_BUTTON_REASON_SHEET_LOADING",
    "INSTALL_BUTTON_REASON_SHEET_NOT_READY",
    "INSTALL_BUTTON_REASON_UNSUPPORTED_GPU",
]
